CREATE USER grafana WITH PASSWORD 'grafana';
CREATE DATABASE grafana OWNER grafana;
CREATE DATABASE ip2location OWNER grafana;
CREATE OR REPLACE FUNCTION batch_ip_geo(TEXT) RETURNS TABLE(ip_addr TEXT, city VARCHAR(128), latitude VARCHAR(20), longitude VARCHAR(20)) AS $BODY$ 
BEGIN
END
$BODY$ LANGUAGE plpgsql IMMUTABLE STRICT;