{
 "title": "Assets in Registered Namespaces",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "domains",
    "label": "Namespaces",
    "query": "SELECT DISTINCT substring(zone.name from '(([a-zA-Z0-9]{1}|[_a-zA-Z0-9]{1}[_a-zA-Z0-9-]{0,61}[a-zA-Z0-9]{1})[.]{1}[a-zA-Z]{2,61}$)') AS name FROM ((SELECT id, content->>'name' as name FROM assets WHERE type = 'FQDN' \nAND id IN (SELECT from_asset_id FROM relations WHERE type = 'node')) as zone \nINNER JOIN relations ON zone.id = relations.from_asset_id) \nWHERE relations.type = 'mx_record'"
   },
   {
    "name": "subs",
    "query": "SELECT fqdns.content->>'name' AS \"FQDN\" FROM ((assets AS fqdns \nINNER JOIN relations ON fqdns.id = relations.from_asset_id) \nINNER JOIN assets AS target ON relations.to_asset_id = target.id) \nWHERE fqdns.type = 'FQDN' AND target.type IN ('FQDN', 'IPAddress')\nAND relations.type IN ('a_record', 'aaaa_record', 'cname_record')\nAND fqdns.content->>'name' SIMILAR TO '%${domains:regex}'\nAND relations.last_seen > '${__from:date:iso}' AND relations.last_seen < '${__to:date:iso}'"
   },
   {
    "name": "addresses",
    "query": "SELECT DISTINCT ip_addr FROM names_to_addrs('${subs:csv}', '${__from:date:iso}', '${__to:date:iso}')"
   },
   {
    "name": "organizations",
    "query": "SELECT orgs.content->>'name' AS \"Organization\" \nFROM ((((((assets AS ips  \nINNER JOIN relations AS rels1 ON ips.id = rels1.to_asset_id) \nINNER JOIN assets AS nets ON rels1.from_asset_id = nets.id) \nINNER JOIN relations AS rels2 ON nets.id = rels2.to_asset_id) \nINNER JOIN assets AS asns ON rels2.from_asset_id = asns.id) \nINNER JOIN relations AS rels3 ON asns.id = rels3.from_asset_id) \nINNER JOIN assets AS orgs ON rels3.to_asset_id = orgs.id) \nWHERE rels1.type = 'contains' AND ips.type = 'IPAddress' \nAND nets.type = 'Netblock' AND rels2.type = 'announces' AND rels3.type = 'managed_by' \nAND orgs.type = 'RIROrg' AND asns.type = 'ASN' AND nets.type = 'Netblock' \nAND rels2.last_seen >= '${__from:date:iso}' AND rels2.last_seen <= '${__to:date:iso}' \nAND rels3.last_seen >= '${__from:date:iso}' AND rels3.last_seen <= '${__to:date:iso}' \nAND ips.content->>'address' IN (${addresses})"
   },
   {
    "name": "geoips",
    "query": "SELECT ips.content->>'address' AS \"IP Address\" \nFROM ((((((assets AS ips  \nINNER JOIN relations AS rels1 ON ips.id = rels1.to_asset_id) \nINNER JOIN assets AS nets ON rels1.from_asset_id = nets.id) \nINNER JOIN relations AS rels2 ON nets.id = rels2.to_asset_id) \nINNER JOIN assets AS asns ON rels2.from_asset_id = asns.id) \nINNER JOIN relations AS rels3 ON asns.id = rels3.from_asset_id) \nINNER JOIN assets AS orgs ON rels3.to_asset_id = orgs.id) \nWHERE rels1.type = 'contains' AND ips.type = 'IPAddress' \nAND nets.type = 'Netblock' AND rels2.type = 'announces' AND rels3.type = 'managed_by' \nAND orgs.type = 'RIROrg' AND asns.type = 'ASN' AND nets.type = 'Netblock' \nAND rels2.last_seen >= '${__from:date:iso}' AND rels2.last_seen <= '${__to:date:iso}' \nAND rels3.last_seen >= '${__from:date:iso}' AND rels3.last_seen <= '${__to:date:iso}'  \nAND ips.content->>'address' SIMILAR TO '%${ips:regex}%'  \nAND nets.content->>'cidr' SIMILAR TO '%${cidrs:regex}%' \nAND asns.content->>'number' SIMILAR TO '%${asns:regex}%' \nAND orgs.content->>'name' SIMILAR TO '%${orgs:regex}%' \nAND ips.content->>'address' IN (${addresses}) \nAND orgs.content->>'name' IN (${organizations})"
   },
   { "name": "geocity", "query": "select ''" },
   {
    "name": "geolist",
    "query": "SELECT * FROM unnest(string_to_array('${addresses:csv}', ',')) WHERE '${geocity:raw}' = '' \nUNION \nSELECT ip_addr FROM batch_ip_geo('${addresses:csv}') \nWHERE city = '${geocity:raw}'"
   },
   { "name": "fqdns", "label": "FQDNs" },
   { "name": "ips", "label": "IP Addresses" },
   { "name": "cidrs", "label": "Netblocks" },
   { "name": "asns", "label": "ASNs" },
   { "name": "orgs", "label": "Organizations" }
  ]
 },
 "panels": [
  {
   "title": "FQDNs Discovered",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) as \"Total\" FROM assets WHERE type = 'FQDN' and content->>'name' IN (${subs})"
    },
    {
     "rawSql": "SELECT fqdn AS \"FQDN\", ip_addr AS \"IP Address\" \nFROM names_to_addrs('${subs:csv}', '${__from:date:iso}', '${__to:date:iso}') \nWHERE fqdn SIMILAR TO '%${fqdns:regex}%'"
    },
    {
     "rawSql": "SELECT ips.content->>'address' AS \"IP Address\", nets.content->>'cidr' AS \"Netblock\", \nasns.content->>'number' AS \"ASN\", orgs.content->>'name' AS \"Organization\" \nFROM ((((((assets AS ips  \nINNER JOIN relations AS rels1 ON ips.id = rels1.to_asset_id) \nINNER JOIN assets AS nets ON rels1.from_asset_id = nets.id) \nINNER JOIN relations AS rels2 ON nets.id = rels2.to_asset_id) \nINNER JOIN assets AS asns ON rels2.from_asset_id = asns.id) \nINNER JOIN relations AS rels3 ON asns.id = rels3.from_asset_id) \nINNER JOIN assets AS orgs ON rels3.to_asset_id = orgs.id) \nWHERE rels1.type = 'contains' AND ips.type = 'IPAddress' \nAND nets.type = 'Netblock' AND rels2.type = 'announces' AND rels3.type = 'managed_by' \nAND orgs.type = 'RIROrg' AND asns.type = 'ASN' AND nets.type = 'Netblock' \nAND rels2.last_seen >= '${__from:date:iso}' AND rels2.last_seen <= '${__to:date:iso}' \nAND rels3.last_seen >= '${__from:date:iso}' AND rels3.last_seen <= '${__to:date:iso}' \nAND ips.content->>'address' SIMILAR TO '%${ips:regex}%' \nAND nets.content->>'cidr' SIMILAR TO '%${cidrs:regex}%' \nAND asns.content->>'number' SIMILAR TO '%${asns:regex}%' \nAND orgs.content->>'name' SIMILAR TO '%${orgs:regex}%' \nAND orgs.content->>'name' IN (${organizations}) AND ips.content->>'address' IN (${geolist})"
    }
   ]
  },
  {
   "title": "Days of Staleness",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT extract(day from date_trunc('day', age(last_seen))) AS interval FROM assets WHERE type = 'FQDN' AND content->>'name' IN (${subs})"
    }
   ]
  },
  {
   "type": "geomap",
   "gridPos": { "h": 18, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT ip_addr AS \"IP Address\", city AS \"City\", latitude AS \"Latitude\", longitude AS \"Longitude\" FROM batch_ip_geo('${geoips:csv}')"
    }
   ]
  },
  {
   "title": "Hosting Organizations",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 11, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT ips.content->>'address' AS \"IP Address\", nets.content->>'cidr' AS \"Netblock\", \nasns.content->>'number' AS \"ASN\", orgs.content->>'name' AS \"Organization\" \nFROM ((((((assets AS ips  \nINNER JOIN relations AS rels1 ON ips.id = rels1.to_asset_id) \nINNER JOIN assets AS nets ON rels1.from_asset_id = nets.id) \nINNER JOIN relations AS rels2 ON nets.id = rels2.to_asset_id) \nINNER JOIN assets AS asns ON rels2.from_asset_id = asns.id) \nINNER JOIN relations AS rels3 ON asns.id = rels3.from_asset_id) \nINNER JOIN assets AS orgs ON rels3.to_asset_id = orgs.id) \nWHERE rels1.type = 'contains' AND ips.type = 'IPAddress' \nAND nets.type = 'Netblock' AND rels2.type = 'announces' AND rels3.type = 'managed_by' \nAND orgs.type = 'RIROrg' AND asns.type = 'ASN' AND nets.type = 'Netblock' \nAND rels2.last_seen >= '${__from:date:iso}' AND rels2.last_seen <= '${__to:date:iso}' \nAND rels3.last_seen >= '${__from:date:iso}' AND rels3.last_seen <= '${__to:date:iso}' \nAND ips.content->>'address' IN (${addresses})"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 26, "w": 24, "x": 0, "y": 18 },
   "targets": [
    { "panelId": 2 }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 44 },
   "options": {
    "content": "The OWASP Amass Project uses the [IP2Location LITE](https://lite.ip2location.com) database for IP geolocation."
   }
  }
 ]
}